name: snap2pay_flutter
description: Flutter clone of Snap 2 Pay 


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  flutter_bloc: ^5.0.1
  equatable: ^1.2.2
  meta: ^1.1.6
  firebase_database: ^3.1.6
  rxdart: ^0.24.1
  cloud_firestore: ^0.13.7
  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - assets/images/

